name: PR Preview
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

permissions:
  contents: write
  pull-requests: write

jobs:
  preview:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@v1
        id: pr-preview
        with:
          source-dir: .
          preview-branch: main
          umbrella-dir: requests
          qr-code: false
          comment: false

      - name: Find files matching "*.rs" or "*.md"
        uses: jeertmans/filesfinder@latest
        id: ff # Any id, to be used later to reference to files output
        with:
          # Only argument, a single string, to be passed as arguments to ff.
          # See `ff --help` for more help.
          # Default: "*"
          args: report.json
      - name: Print files
        run: echo "${{ steps.ff.outputs.files }}"

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v5
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.pr-preview.outputs.preview-url }}/${{ steps.ff.outputs.files[0] }}

  cleanup:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup PR Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: .
          preview-branch: main
          umbrella-dir: requests
          action: remove
